[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.ruff]
line-length = 88
target-version = "py310"
extend-select = ["I", "C4", "SIM"]
exclude = ["venv", "__pycache__", "migrations"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
strict = true
